export { };

/**
 * MODULE 1: INTRODUCTION & SETUP
 * Topic: Interoperability
 * 
 * THEORY:
 * TypeScript compiles down to JavaScript. Browsers and Node.js don't understand TypeScript directly.
 * They execute the JavaScript output generated by the TypeScript compiler (tsc).
 * 
 * Any valid JavaScript code is also valid TypeScript code (mostly).
 * You can incrementally adopt TypeScript in a JavaScript project.
 */

// --- CODE: TS compiles to JS ---

// This TypeScript code...
const greeting: string = "Hello, World!";

function greet(name: string): void {
    console.log(`${greeting} ${name}`);
}

greet("Developer");

// ...compiles to this JavaScript (roughly):
// "use strict";
// const greeting = "Hello, World!";
// function greet(name) {
//     console.log(`${greeting} ${name}`);
// }

// --- BAD CODE (Uncomment to see errors) ---

// const x = 10;
// x = "string"; 
// Error: Assignment to constant variable (JS error caught by TS).

// --- TASK ---
// TODO: Run `npx tsc 01-introduction/02-interoperability.ts` in your terminal.
// Check the generated .js file (or output) to see how types are removed.
