"""
04_hash_tables.py

This module covers Hash Tables (Dictionaries in Python).
"""

# -----------------------------------------------------------------------------
# 1. Hash Table
# -----------------------------------------------------------------------------
# In Python, the Dictionary data types represent the implementation of hash tables.
# The Keys in the dictionary satisfy the following requirements:
# - The keys of the dictionary are hashable i.e. the are generated by hashing function which generates unique result for each unique value supplied to the hash function.
# - The order of data elements in a dictionary is not fixed.

print("--- Hash Table (Dictionary) ---")

# Declare a dictionary
dict = {'Name': 'Zara', 'Age': 7, 'Class': 'First'}

# Accessing the dictionary with its key
print(f"dict['Name']: {dict['Name']}")
print(f"dict['Age']: {dict['Age']}")

# Updating
dict['Age'] = 8
print(f"Updated Age: {dict['Age']}")

# Adding
dict['School'] = "DPS School"
print(f"Added School: {dict['School']}")

# Deleting
del dict['Name'] # remove entry with key 'Name'
print(f"Dictionary after deletion: {dict}")

# -----------------------------------------------------------------------------
# 2. Hashing Function
# -----------------------------------------------------------------------------
# Python has a built-in hash() function.

print("\n--- hash() Function ---")
print(f"hash('Zara'): {hash('Zara')}")
print(f"hash(100): {hash(100)}")
print(f"hash((1, 2)): {hash((1, 2))}") # Tuple is hashable
# print(hash([1, 2])) # List is NOT hashable (TypeError)
